version: "3"

services:
  angular-app:
    image: sofienechihi/my-repo:chatbot-store-fronten
    ports:
      - "80:80"

  golang-app:
    image: sofienechihi/my-repo:chatbot-store-backend
    ports:
      - "9911:9911"
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis
    container_name: redis-db-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo
    container_name: mongo-db-container
    ports:
      - "27017:27017"
    env_file:
      - .container.env
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  redis_data:
  mongodb_data:
