name: Docker Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Angular frontend Docker image
        run: |
          cd frontend
          docker build -t sofienechihi/my-repo:chatbot-store-frontend .

      - name: Retrieve and decode secret
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" | base64 --decode > backend/.env
    
      - name: Build Golang backend Docker image
        run: |
          cd backend
          docker build -t sofienechihi/my-repo:chatbot-store-backend .

      - name: Push Docker images to DockerHub
        run: |
          docker push sofienechihi/my-repo:chatbot-store-frontend
          docker push sofienechihi/my-repo:chatbot-store-backend
